services:
  bet_maker_db:
    image: postgres
    container_name: bet_maker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata_bet_maker:/var/lib/postgresql/data

  line_provider_db:
    image: postgres
    container_name: line_provider_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata_line_provider:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - backend_network
    volumes:
      - redis_data:/data

  bet_maker:
    build: ./bet-maker
    container_name: bet_maker
    ports:
      - "8000:8000"
    env_file:
      - ./bet-maker/.env.docker
    depends_on:
      bet_maker_db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - backend_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  line_provider:
    build: ./line-provider
    container_name: line_provider
    ports:
      - "8001:8001"
    env_file:
      - ./line-provider/.env.docker
    depends_on:
      line_provider_db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - backend_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

volumes:
  pgdata_bet_maker:
  pgdata_line_provider:
  redis_data:

networks:
  backend_network:
    driver: bridge
