"""
Db creation.

Revision ID: 71a29d2b4718
Revises:
Create Date: 2024-08-03 15:50:59.186105

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71a29d2b4718"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("bets",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("event_id", sa.Integer(), nullable=False),
    sa.Column("bet_prediction", sa.Enum("FIRST_TEAM_WIN", "SECOND_TEAM_WIN", name="betprediction"), nullable=False),
    sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column("status", sa.Enum("NOT_PLAYED", "WON", "LOST", name="betstatus"), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bets")
    # ### end Alembic commands ###
